// Content manifest — vowel-group-ready, scalable structure
// Populate vowelGroups with real content when ready

export const lessonContent = {
  vowelGroups: [
    {
      id: "short-a",
      label: "Short A",
      emoji: "🍎",
      color: "#FF6B6B",
      available: false,
      words: [],
    },
    {
      id: "short-e",
      label: "Short E",
      emoji: "🥚",
      color: "#FFD93D",
      available: false,
      words: [],
    },
    {
      id: "short-i",
      label: "Short I",
      emoji: "🐛",
      color: "#6BCB77",
      available: false,
      words: [],
    },
    {
      id: "short-o",
      label: "Short O",
      emoji: "🐙",
      color: "#4D96FF",
      available: false,
      words: [],
    },
    {
      id: "short-u",
      label: "Short U",
      emoji: "☂️",
      color: "#C77DFF",
      available: false,
      words: [],
    },
  ],
};

export const activityTypes = [
  {
    id: "tap-sounds",
    label: "Tap Sounds",
    emoji: "🔊",
    description: "Tap each letter and hear its sound",
    color: "#4ECDC4",
    bgColor: "#E8FFFE",
    available: true,
  },
  {
    id: "blend-listen",
    label: "Blend & Listen",
    emoji: "🔗",
    description: "Listen as sounds blend into a word",
    color: "#FFD93D",
    bgColor: "#FFFDE7",
    available: true,
  },
  {
    id: "choose-picture",
    label: "Choose Picture",
    emoji: "🖼️",
    description: "Hear a word and tap the right picture",
    color: "#6BCB77",
    bgColor: "#F0FFF4",
    available: true,
  },
  {
    id: "drag-letters",
    label: "Drag Letters",
    emoji: "✋",
    description: "Drag letters to build the word",
    color: "#4D96FF",
    bgColor: "#EFF6FF",
    available: true,
  },
  {
    id: "spell-word",
    label: "Spell the Word",
    emoji: "✏️",
    description: "See a picture and spell the word",
    color: "#C77DFF",
    bgColor: "#FAF0FF",
    available: true,
  },
];

export const games = [
  {
    id: "pic-slice",
    label: "Rearrange the Pictures",
    emoji: "🖼️",
    description: "Drag picture pieces into the right order",
    available: true,
  },
  {
    id: "word-match",
    label: "Word Match",
    emoji: "🎯",
    description: "Match the word to the picture",
    available: true,
  },
  {
    id: "drag-letters",
    label: "Drag the Letters",
    emoji: "✋",
    description: "Drag letters into the right boxes to spell the word",
    available: true,
  },
  {
    id: "missing-sound",
    label: "Missing Sound",
    emoji: "❓",
    description: "Find the missing letter to complete the word",
    available: true,
  },
  {
    id: "letter-catch",
    label: "Letter Catch",
    emoji: "🧩",
    description: "Catch the right letters to make a word",
    available: true,
  },
  {
    id: "sound-safari",
    label: "Sound Safari",
    emoji: "🦁",
    description: "Find animals whose names start with the sound",
    available: false,
  },
  {
    id: "drag-letters-v2",
    label: "Drag the Letters V2",
    emoji: "✍️",
    description: "Place all letters then hit Submit to check your answer",
    available: true,
  },
  {
    id: "missing-sound-01",
    label: "Missing Sound 0.1",
    emoji: "🔤",
    description: "Tap a letter to hear it · Drag it to fill the missing sound",
    available: true,
  },
  {
    id: "draw-line",
    label: "Draw a Line",
    emoji: "〰️",
    description: "Listen and match pictures to their letter sounds by drawing a line",
    available: true,
  },
  {
    id: "letter-sound-connection",
    label: "Letter to Sound Connection",
    emoji: "🔗",
    description: "Connect each letter to its picture slice by drawing a line",
    available: true,
  },
  {
    id: "write-short-a",
    label: "Write — Short A",
    emoji: "✏️",
    description: "Trace letters and write short-a words with your finger",
    available: false,
  },
  {
    id: "write-short-e",
    label: "Write — Short E",
    emoji: "✏️",
    description: "Trace letters and write short-e words with your finger",
    available: false,
  },
  {
    id: "write-short-i",
    label: "Write — Short I",
    emoji: "✏️",
    description: "Trace letters and write short-i words with your finger",
    available: false,
  },
  {
    id: "write-short-o",
    label: "Write — Short O",
    emoji: "✏️",
    description: "Trace letters and write short-o words with your finger",
    available: false,
  },
  {
    id: "write-short-u",
    label: "Write — Short U",
    emoji: "✏️",
    description: "Trace letters and write short-u words with your finger",
    available: false,
  },
];