const BASE = "https://raw.githubusercontent.com/Mr-Banjoko/learn-with-cody/main/phonics_app_images/cvc_words/a_vowel";

export const shortAWords = [
  { word: "cat", image: `${BASE}/cat.webp` },
  { word: "dad", image: `${BASE}/dad.webp` },
  { word: "rat", image: `${BASE}/rat.webp` },
  { word: "hat", image: `${BASE}/hat.webp` },
  { word: "bat", image: `${BASE}/bat.webp` },
  { word: "can", image: `${BASE}/can.webp` },
  { word: "pan", image: `${BASE}/pan.webp` },
  { word: "jam", image: `${BASE}/jam.webp` },
  { word: "map", image: `${BASE}/map.webp` },
  { word: "mat", image: `${BASE}/mat.webp` },
  { word: "sad", image: `${BASE}/sad.webp` },
  { word: "sat", image: `${BASE}/sat.webp` },
  { word: "pat", image: `${BASE}/pat.webp` },
  { word: "mad", image: `${BASE}/mad.webp` },
  { word: "ham", image: `${BASE}/ham.webp` },
  { word: "gas", image: `${BASE}/gas.webp` },
  { word: "jar", image: `${BASE}/jar.webp` },
  { word: "tag", image: `${BASE}/tag.webp` },
  { word: "tap", image: `${BASE}/tap.webp` },
  { word: "bag", image: `${BASE}/bag.webp` },
  { word: "gap", image: `${BASE}/gap.webp` },
  { word: "wax", image: `${BASE}/wax.webp` },
  { word: "tan", image: `${BASE}/tan.webp` },
  { word: "tax", image: `${BASE}/tax.webp` },
  { word: "dam", image: `${BASE}/dam.webp` },
  { word: "cab", image: `${BASE}/cab.webp` },
  { word: "lad", image: `${BASE}/lad.webp` },
  { word: "lab", image: `${BASE}/lab.webp` },
  { word: "pal", image: `${BASE}/pal.webp` },
  { word: "ban", image: `${BASE}/ban.webp` },
  { word: "dab", image: `${BASE}/dab.webp` },
  { word: "fan", image: `${BASE}/fan.webp` },
  { word: "jab", image: `${BASE}/jab.webp` },
  { word: "man", image: `${BASE}/man.webp` },
  { word: "nab", image: `${BASE}/nab.webp` },
  { word: "rag", image: `${BASE}/rag.webp` },
  { word: "ram", image: `${BASE}/ram.webp` },
  { word: "ran", image: `${BASE}/ran.webp` },
  { word: "sap", image: `${BASE}/sap.webp` },
  { word: "nap", image: `${BASE}/nap.webp` },
  { word: "fat", image: `${BASE}/fat.webp` },
];