const BASE = "https://raw.githubusercontent.com/Mr-banjoko/learn-with-cody/main/phonics_app_images/cvc_words/a_vowel";

export const shortAWords = [
  { word: "cat", image: `${BASE}/cat.png` },
  { word: "dad", image: `${BASE}/dad.png` },
  { word: "rat", image: `${BASE}/rat.png` },
  { word: "hat", image: `${BASE}/hat.png` },
  { word: "bat", image: `${BASE}/bat.png` },
  { word: "can", image: `${BASE}/can.png` },
  { word: "pan", image: `${BASE}/pan.png` },
  { word: "jam", image: `${BASE}/jam.png` },
  { word: "map", image: `${BASE}/map.png` },
  { word: "mat", image: `${BASE}/mat.png` },
  { word: "sad", image: `${BASE}/sad.png` },
  { word: "sat", image: `${BASE}/sat.png` },
  { word: "pat", image: `${BASE}/pat.png` },
  { word: "mad", image: `${BASE}/mad.png` },
  { word: "ham", image: `${BASE}/ham.png` },
  { word: "gas", image: `${BASE}/gas.png` },
  { word: "jar", image: `${BASE}/jar.png` },
  { word: "tag", image: `${BASE}/tag.png` },
  { word: "tap", image: `${BASE}/tap.png` },
  { word: "bag", image: `${BASE}/bag.png` },
  { word: "gap", image: `${BASE}/gap.png` },
  { word: "wax", image: `${BASE}/wax.png` },
  { word: "tan", image: `${BASE}/tan.png` },
  { word: "tax", image: `${BASE}/tax.png` },
  { word: "dam", image: `${BASE}/dam.png` },
  { word: "cab", image: `${BASE}/cab.png` },
  { word: "lad", image: `${BASE}/lad.png` },
  { word: "lab", image: `${BASE}/lab.png` },
  { word: "pal", image: `${BASE}/pal.png` },
  { word: "ban", image: `${BASE}/ban.png` },
  { word: "dab", image: `${BASE}/dab.png` },
];