const BASE = "https://raw.githubusercontent.com/Mr-Banjoko/learn-with-cody/main/phonics_app_images/cvc_words/o_vowel";

export const shortOWords = [
  { word: "mom", image: `${BASE}/mom.webp` },
  { word: "dog", image: `${BASE}/dog.webp` },
  { word: "hot", image: `${BASE}/hot.webp` },
  { word: "top", image: `${BASE}/top.webp` },
  { word: "pop", image: `${BASE}/pop.webp` },
  { word: "not", image: `${BASE}/not.webp` },
  { word: "hop", image: `${BASE}/hop.webp` },
  { word: "log", image: `${BASE}/log.webp` },
  { word: "rod", image: `${BASE}/rod.webp` },
  { word: "rob", image: `${BASE}/rob.webp` },
  { word: "pot", image: `${BASE}/pot.webp` },
  { word: "mop", image: `${BASE}/mop.webp` },
  { word: "box", image: `${BASE}/box.webp` },
  { word: "fox", image: `${BASE}/fox.webp` },
  { word: "jog", image: `${BASE}/jog.webp` },
  { word: "sob", image: `${BASE}/sob.webp` },
  { word: "cod", image: `${BASE}/cod.webp` },
  { word: "cop", image: `${BASE}/cop.webp` },
  { word: "cot", image: `${BASE}/cot.webp` },
  { word: "bog", image: `${BASE}/bog.webp` },
  { word: "hog", image: `${BASE}/hog.webp` },
  { word: "fog", image: `${BASE}/fog.webp` },
  { word: "cob", image: `${BASE}/cob.webp` },
  { word: "cog", image: `${BASE}/cog.webp` },
  { word: "jot", image: `${BASE}/jot.webp` },
];