const BASE = "https://raw.githubusercontent.com/Mr-Banjoko/learn-with-cody/main/phonics_app_images/cvc_words/i_vowel";

export const shortIWords = [
  { word: "sit", image: `${BASE}/sit.webp` },
  { word: "pin", image: `${BASE}/pin.webp` },
  { word: "pig", image: `${BASE}/pig.webp` },
  { word: "hit", image: `${BASE}/hit.webp` },
  { word: "win", image: `${BASE}/win.webp` },
  { word: "kid", image: `${BASE}/kid.webp` },
  { word: "lip", image: `${BASE}/lip.webp` },
  { word: "tin", image: `${BASE}/tin.webp` },
  { word: "tip", image: `${BASE}/tip.webp` },
  { word: "hip", image: `${BASE}/hip.webp` },
  { word: "kit", image: `${BASE}/kit.webp` },
  { word: "mix", image: `${BASE}/mix.webp` },
  { word: "fix", image: `${BASE}/fix.webp` },
  { word: "rib", image: `${BASE}/rib.webp` },
  { word: "sip", image: `${BASE}/sip.webp` },
  { word: "zip", image: `${BASE}/zip.webp` },
  { word: "hid", image: `${BASE}/hid.webp` },
  { word: "rid", image: `${BASE}/rid.webp` },
  { word: "fin", image: `${BASE}/fin.webp` },
  { word: "fit", image: `${BASE}/fit.webp` },
  { word: "bit", image: `${BASE}/bit.webp` },
  { word: "big", image: `${BASE}/big.webp` },
  { word: "pit", image: `${BASE}/pit.webp` },
  { word: "bin", image: `${BASE}/bin.webp` },
  { word: "dig", image: `${BASE}/dig.webp` },
  { word: "rip", image: `${BASE}/rip.webp` },
  { word: "dip", image: `${BASE}/dip.webp` },
  { word: "rim", image: `${BASE}/rim.webp` },
  { word: "lid", image: `${BASE}/lid.webp` },
  { word: "six", image: `${BASE}/six.webp` },
  { word: "fig", image: `${BASE}/fig.webp` },
  { word: "wig", image: `${BASE}/wig.webp` },
  { word: "dim", image: `${BASE}/dim.webp` },
  { word: "jig", image: `${BASE}/jig.webp` },
  { word: "gig", image: `${BASE}/gig.webp` },
  { word: "bib", image: `${BASE}/bib.webp` },
];