const BASE = "https://raw.githubusercontent.com/Mr-Banjoko/learn-with-cody/main/phonics_app_images/cvc_words/i_vowel";
const AUDIO = "https://raw.githubusercontent.com/Mr-Banjoko/learn-with-cody/audio-feature/letter_sound/words/i_words";

export const shortIWords = [
  { word: "sit", image: `${BASE}/sit.webp`, audio: `${AUDIO}/sit.mp3` },
  { word: "pin", image: `${BASE}/pin.webp`, audio: `${AUDIO}/pin.mp3` },
  { word: "pig", image: `${BASE}/pig.webp`, audio: `${AUDIO}/pig.mp3` },
  { word: "hit", image: `${BASE}/hit.webp`, audio: `${AUDIO}/hit.mp3` },
  { word: "win", image: `${BASE}/win.webp`, audio: `${AUDIO}/win.mp3` },
  { word: "kid", image: `${BASE}/kid.webp`, audio: `${AUDIO}/kid.mp3` },
  { word: "lip", image: `${BASE}/lip.webp`, audio: `${AUDIO}/lip.mp3` },
  { word: "tin", image: `${BASE}/tin.webp`, audio: `${AUDIO}/tin.mp3` },
  { word: "tip", image: `${BASE}/tip.webp`, audio: `${AUDIO}/tip.mp3` },
  { word: "hip", image: `${BASE}/hip.webp`, audio: `${AUDIO}/hip.mp3` },
  { word: "kit", image: `${BASE}/kit.webp`, audio: `${AUDIO}/kit.mp3` },
  { word: "mix", image: `${BASE}/mix.webp`, audio: `${AUDIO}/mix.mp3` },
  { word: "fix", image: `${BASE}/fix.webp`, audio: `${AUDIO}/fix.mp3` },
  { word: "rib", image: `${BASE}/rib.webp`, audio: `${AUDIO}/rib.mp3` },
  { word: "sip", image: `${BASE}/sip.webp`, audio: `${AUDIO}/sip.mp3` },
  { word: "zip", image: `${BASE}/zip.webp`, audio: `${AUDIO}/zip.mp3` },
  { word: "hid", image: `${BASE}/hid.webp`, audio: `${AUDIO}/hid.mp3` },
  { word: "rid", image: `${BASE}/rid.webp`, audio: `${AUDIO}/rid.mp3` },
  { word: "fin", image: `${BASE}/fin.webp`, audio: `${AUDIO}/fin.mp3` },
  { word: "fit", image: `${BASE}/fit.webp`, audio: `${AUDIO}/fit.mp3` },
  { word: "bit", image: `${BASE}/bit.webp`, audio: `${AUDIO}/bit.mp3` },
  { word: "big", image: `${BASE}/big.webp`, audio: `${AUDIO}/big.mp3` },
  { word: "pit", image: `${BASE}/pit.webp`, audio: `${AUDIO}/pit.mp3` },
  { word: "bin", image: `${BASE}/bin.webp`, audio: `${AUDIO}/bin.mp3` },
  { word: "dig", image: `${BASE}/dig.webp`, audio: `${AUDIO}/dig.mp3` },
  { word: "rip", image: `${BASE}/rip.webp`, audio: `${AUDIO}/rip.mp3` },
  { word: "dip", image: `${BASE}/dip.webp`, audio: `${AUDIO}/dip.mp3` },
  { word: "rim", image: `${BASE}/rim.webp`, audio: `${AUDIO}/rim.mp3` },
  { word: "lid", image: `${BASE}/lid.webp`, audio: `${AUDIO}/lid.mp3` },
  { word: "six", image: `${BASE}/six.webp`, audio: `${AUDIO}/six.mp3` },
  { word: "fig", image: `${BASE}/fig.webp`, audio: `${AUDIO}/fig.mp3` },
  { word: "wig", image: `${BASE}/wig.webp`, audio: `${AUDIO}/wig.mp3` },
  { word: "dim", image: `${BASE}/dim.webp`, audio: `${AUDIO}/dim.mp3` },
  { word: "jig", image: `${BASE}/jig.webp`, audio: `${AUDIO}/jig.mp3` },
  { word: "gig", image: `${BASE}/gig.webp`, audio: `${AUDIO}/gig.mp3` },
  { word: "bib", image: `${BASE}/bib.webp`, audio: `${AUDIO}/bib.mp3` },
];