const BASE = "https://raw.githubusercontent.com/Mr-Banjoko/learn-with-cody/main/phonics_app_images/cvc_words/a_vowel";
const AUDIO = "https://raw.githubusercontent.com/Mr-Banjoko/learn-with-cody/audio-feature/letter_sound/words/a_words";

export const shortAWords = [
  { word: "cat", image: `${BASE}/cat.webp`, audio: `${AUDIO}/cat.mp3` },
  { word: "dad", image: `${BASE}/dad.webp`, audio: `${AUDIO}/dad.mp3` },
  { word: "rat", image: `${BASE}/rat.webp`, audio: `${AUDIO}/rat.mp3` },
  { word: "hat", image: `${BASE}/hat.webp`, audio: `${AUDIO}/hat.mp3` },
  { word: "bat", image: `${BASE}/bat.webp`, audio: `${AUDIO}/bat.mp3` },
  { word: "can", image: `${BASE}/can.webp`, audio: `${AUDIO}/can.mp3` },
  { word: "pan", image: `${BASE}/pan.webp`, audio: `${AUDIO}/pan.mp3` },
  { word: "jam", image: `${BASE}/jam.webp`, audio: `${AUDIO}/jam.mp3` },
  { word: "map", image: `${BASE}/map.webp`, audio: `${AUDIO}/map.mp3` },
  { word: "mat", image: `${BASE}/mat.webp`, audio: `${AUDIO}/mat.mp3` },
  { word: "sad", image: `${BASE}/sad.webp`, audio: `${AUDIO}/sad.mp3` },
  { word: "sat", image: `${BASE}/sat.webp`, audio: `${AUDIO}/sat.mp3` },
  { word: "pat", image: `${BASE}/pat.webp`, audio: `${AUDIO}/pat.mp3` },
  { word: "mad", image: `${BASE}/mad.webp`, audio: `${AUDIO}/mad.mp3` },
  { word: "ham", image: `${BASE}/ham.webp`, audio: `${AUDIO}/ham.mp3` },
  { word: "gas", image: `${BASE}/gas.webp`, audio: `${AUDIO}/gas.mp3` },
  { word: "jar", image: `${BASE}/jar.webp`, audio: `${AUDIO}/jar.mp3` },
  { word: "tag", image: `${BASE}/tag.webp`, audio: `${AUDIO}/tag.mp3` },
  { word: "tap", image: `${BASE}/tap.webp`, audio: `${AUDIO}/tap.mp3` },
  { word: "bag", image: `${BASE}/bag.webp`, audio: `${AUDIO}/bag.mp3` },
  { word: "gap", image: `${BASE}/gap.webp`, audio: `${AUDIO}/gap.mp3` },
  { word: "wax", image: `${BASE}/wax.webp`, audio: `${AUDIO}/wax.mp3` },
  { word: "tan", image: `${BASE}/tan.webp`, audio: `${AUDIO}/tan.mp3` },
  { word: "tax", image: `${BASE}/tax.webp`, audio: `${AUDIO}/tax.mp3` },
  { word: "dam", image: `${BASE}/dam.webp`, audio: `${AUDIO}/dam.mp3` },
  { word: "cab", image: `${BASE}/cab.webp`, audio: `${AUDIO}/cab.mp3` },
  { word: "lad", image: `${BASE}/lad.webp`, audio: `${AUDIO}/lad.mp3` },
  { word: "lab", image: `${BASE}/lab.webp`, audio: `${AUDIO}/lab.mp3` },
  { word: "pal", image: `${BASE}/pal.webp`, audio: `${AUDIO}/pal.mp3` },
  { word: "ban", image: `${BASE}/ban.webp`, audio: `${AUDIO}/ban.mp3` },
  { word: "dab", image: `${BASE}/dab.webp`, audio: `${AUDIO}/dab.mp3` },
  { word: "fan", image: `${BASE}/fan.webp`, audio: `${AUDIO}/fan.mp3` },
  { word: "jab", image: `${BASE}/jab.webp`, audio: `${AUDIO}/jab.mp3` },
  { word: "man", image: `${BASE}/man.webp`, audio: `${AUDIO}/man.mp3` },
  { word: "nab", image: `${BASE}/nab.webp`, audio: `${AUDIO}/nab.mp3` },
  { word: "rag", image: `${BASE}/rag.webp`, audio: `${AUDIO}/rag.mp3` },
  { word: "ram", image: `${BASE}/ram.webp`, audio: `${AUDIO}/ram.mp3` },
  { word: "ran", image: `${BASE}/ran.webp`, audio: `${AUDIO}/ran.mp3` },
  { word: "sap", image: `${BASE}/sap.webp`, audio: `${AUDIO}/sap.mp3` },
  { word: "nap", image: `${BASE}/nap.webp`, audio: `${AUDIO}/nap.mp3` },
  { word: "fat", image: `${BASE}/fat.webp`, audio: `${AUDIO}/fat.mp3` },
];